[package]
name = "aef"
version = "0.1.0"
edition = "2018"
authors = ["wyhaya <wyhaya@gmail.com>"]
license = "MIT"
description = "Util for file encryption"
homepage = "https://github.com/wyhaya/aef"
repository = "https://github.com/wyhaya/aef.git"
readme = "README.md"

[profile.release]
lto = true
codegen-units = 1

[profile.dev.package.scrypt]
opt-level = 3

[dependencies]
aes-gcm = "0.9.2"
clap = { version = "2.33.3", default-features = false }
rand = "0.8.4"
rpassword = "5.0.1"
scrypt = "0.7.0"